version: 2
updates:
 - package-ecosystem: "npm"
   directory: "frontend/"
   target-branch: "main"
   schedule:
     interval: "daily"

 - package-ecosystem: "pip"
   directory: "backend/"
   schedule:
     interval: "daily"

 # Github Actions
 - package-ecosystem: "github-actions"
   directory: "frontend/"
   schedule:
     interval: "weekly"
